version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
      time: '09:00'
      day: 'sunday'
    open-pull-requests-limit: 2
    reviewers:
      - 'msudgh'
    versioning-strategy: increase
    groups:
      production-dependencies:
        applies-to: 'security-updates'
        dependency-type: 'production'
